add_newline = true
format = """\
$username\
$hostname\
$directory\
$git_branch\
$golang\
$java\
$nodejs\
$rust\
${custom.pomodoro}
$character\
"""
right_format = """\
$memory_usage\
$battery\
$time\
$line_break\
"""

[username]
format = "[$user@]($style)" 	
show_always = true
[hostname]
ssh_only = false
[git_branch]
symbol = "ï„¦ "
[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"
[[battery.display]]
threshold = 99

[time]
format = " [$time]($style)"
disabled = false

[golang]
symbol = "î˜§ "

[memory_usage]
disabled = false
format = "[${ram} | ${swap}]($style)"

[java]
format = ""
[line_break]
disabled = false
[nodejs]
format = "[$symbol $version](bold green)"
symbol = "ğŸ¤–"
disabled = true

[custom.pomodoro]
command = "pomodoro status"
shell = ["sh"]
